services:
  flask_app: # aplicação flask
    container_name: flask_app # nome do container
    image: isabella/flask_app_img:1.0.0 # imagem usada
    
    build: . # imagem vai ser criada localmente nesse diretório (que tem o dockerfile)
    ports: # mapeia as portas container:host
      - "5000:5000"
    
    environment: # define variáveis de ambiente
      - DB_URL=postgresql://postgres:password@flask_db:5432/postgres 
    depends_on:
      - flask_db # flask_app depende do db, iniciando primeiro o flask_db e dps o app
    
  flask_db: # banco de dados postgres
    container_name: flask_db
    image: postgres # imagem do postgres
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=postgres # usuário 
      - POSTGRES_PASSWORD=postgres # senha
      - POSTGRES_DB=postgres # nome do db 

    volumes:
      - ./cria-tabela-usuarios.sql:/docker-entrypoint-initdb.d/cria-tabela-usuarios.sql
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}

